This is my first github action yaml with changes

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,22 +1,21 @@
 name: 01 - Building Blocks
-on: workflow_dispatch
+on: push
 
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
-  steps:
-    - name: Say hello
-      run: echo "Hello World!"
+    steps:
+      - name: Say hello
+        run: echo "Hello World!"
 
-Jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
-  steps:
-    - name: Failed step
-      run: |
-      echo "I will fail"
-      exit 0
-    - name: Say goodbye
-      run: echo "Goodbye!"  
-     
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye!"  
+      
 
